### ISSUE TITLE
Could you provide the training method? 

### ISSUE THREAD

**Issue by wintercat1994** [tellurion-kanata/colorizeDiffusion#3]
Hello, I have seen the training code, but the training steps and parameters are not provided in your instructions. Could you please supplement them?

**Comment by tellurion-kanata** [comment]
training details will be released with new report soon.

**Comment by xinli2008** [comment]
looking forward to the training instructions.

**Comment by tellurion-kanata** [comment]
> looking forward to the training instructions.

If you just want some training instructions, I believe the arxiv version is comprehensive enough. 
The new paper is much shorter and many important details are deleted.
